### ISSUE TITLE
Create `HTTPObserver.Worker`

### ISSUE THREAD

**Issue by bronsonholden** [bronsonholden/httpizza#44]
This module will be configured as an Oban worker that processes an observer. Roughly speaking, its duties are:

1. Load the `HTTPObserver` from ID received via job arguments
2. Create `HTTPObservation` record
3. For each associated check (as of now—`HTTPHeadCheck` and `HTTPStatusCheck`), perform check
4. Insert an associated check on the `HTTPObservation` record with the results.
5. Insert notification(s)

Checks should run in a separate process, and should have a time limit.

## Finer details

The following things will need to be implemented before a fully-fledged observer process can function:

* [x] ~~Retrieving secrets and interpolating them into strings~~ Post-MVP
* [x] ~~Replacing sensitive strings (i.e. strings that contain secrets) with placeholder/masked info~~ Post-MVP
* [x] `HTTPObservation` implementation, including associations with `HTTPHeadCheck` and `HTTPStatusCheck` #33
* [x] Oban dispatcher job (scans for past-due observers and enqueues a job for them) #7 
* [x] ~~`EmailRecipient` implementation (probably with association via join record to `HTTPObservation`)~~ replaced by #18 
* [x] `email_recipient` column added to `HTTPObserver` #18
* [x] ~~`EmailNotification` schema (that eventually relate to the `EmailRecipient`) that is associated with the `HTTPObservation`~~

## Relevant documentation

[Erlang: `timer`](https://www.erlang.org/doc/man/timer)
[`Elixir.Task`](https://hexdocs.pm/elixir/1.13/Task.html)
[`Finch`](https://hexdocs.pm/finch/Finch.html)
